# 使用多阶段构建
# 第一阶段：构建阶段
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm config set registry http://registry.npm.taobao.org
RUN npm install
COPY . .
RUN npm run build

# 第二阶段：生产阶段
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]